//
//  GraphQLPageResponse.swift
//  Networking
//
//  Created by Alberto Guerrero Martin on 01/09/2026.
//

import Foundation

public struct GraphQLPageResponse<ResponseEntity: Decodable>: Decodable {
    public let info: GraphQLPageInfo
    public let results: [ResponseEntity]

    public init(info: GraphQLPageInfo, results: [ResponseEntity]) {
        self.info = info
        self.results = results
    }
}

// Encodable and Sendable arrive *conditionally* rather than as constraints on
// `ResponseEntity`, so a caller that only ever decodes a page keeps working
// unchanged. Tightening the generic to `Codable & Sendable` would push the same
// requirement up through `GraphQLQuery.ResponseEntity` and onto every entity in
// the app, whether or not it is ever cached. Writing a page back out is what the
// disk cache needs, and only the entities it caches have to pay for it.

extension GraphQLPageResponse: Encodable where ResponseEntity: Encodable {}

extension GraphQLPageResponse: Sendable where ResponseEntity: Sendable {}

public struct GraphQLPageInfo: Codable, Sendable {
    public let count: Int?
    public let pages: Int?
    /// The next page number, or `nil` when you've reached the end.
    public let next: Int?

    public init(count: Int?, pages: Int?, next: Int?) {
        self.count = count
        self.pages = pages
        self.next = next
    }
}

// The selection sets below are written by hand rather than generated by
// `@Document`: the macro's runtime asks whether a property's type conforms to
// `GraphQLDocumentConvertible`, and `[ResponseEntity?]?` is an `Array`, which
// never does — `results` would come out as a bare field with no selection set,
// which is not valid GraphQL. Keeping them next to the types they mirror is
// still what matters: add a property above and you edit the selection set on
// the adjacent line, not a string literal in some query extension.

extension GraphQLPageInfo: GraphQLDocumentConvertible {
    public static func document(depth: Int) -> String {
        """
        count
        pages
        next
        """
    }
}

extension GraphQLPageResponse: GraphQLDocumentConvertible where ResponseEntity: GraphQLDocumentConvertible {
    /// - Note: `depth` is passed straight through to `ResponseEntity` rather than
    ///   decremented. The page wrapper is a transport detail, not a level of the
    ///   schema the caller asked to walk, so spending budget on it would silently
    ///   shrink every paginated selection set by one level.
    public static func document(depth: Int) -> String {
        """
        info { \(GraphQLPageInfo.document(depth: depth)) }
        results { \(ResponseEntity.document(depth: depth)) }
        """
    }
}
