//
//  JustWatchShowEntity.swift
//  Characters
//
//  Created by Alberto Guerrero Martin on 07/09/2026.
//

import Foundation
import Networking

/// A show's seasons and episodes, with the streaming offers JustWatch knows
/// about, exactly as that server describes them.
///
/// **The Characters copy of the Episodes entity.** Feature packages stay
/// independent — importing `Episodes` from here would couple two modules that
/// have no reason to change together — so the tree is duplicated rather than
/// shared. See `JustWatchShowOffersQuery` for why the document below is kept
/// identical to the Episodes one.
///
/// Every property is optional for the same reason `CharacterDetailEntity`'s are
/// — a GraphQL server may legally answer `null` for any field — and here the
/// rule is load-bearing rather than defensive. This endpoint is unofficial:
/// nothing promises the shape will stay as it is, and the *only* thing the
/// feature loses when it changes is a play button on a row. A non-optional
/// anywhere in this tree would turn that into a decoding failure, and a decoding
/// failure would be logged as an error for a link nobody asked for.
///
/// Which of these are actually required is `HBOMaxLinksMapper`'s business, one
/// episode at a time — and its answer is never "fail", only "skip this row".
struct JustWatchShowEntity: Codable, Sendable, Hashable {
    let seasons: [JustWatchSeasonEntity]?
}

/// One season. Its own `content` carries the season number as a fallback for
/// episodes that do not repeat it — see `HBOMaxLinksMapper`.
struct JustWatchSeasonEntity: Codable, Sendable, Hashable {
    let content: JustWatchSeasonContentEntity?
    let episodes: [JustWatchEpisodeEntity]?
}

/// JustWatch splits the localized fields of a node into a `content` object taking
/// a country and a language, so the numbering lives one level deeper than the
/// shape suggests.
struct JustWatchSeasonContentEntity: Codable, Sendable, Hashable {
    let seasonNumber: Int?
}

struct JustWatchEpisodeEntity: Codable, Sendable, Hashable {
    let content: JustWatchEpisodeContentEntity?
    /// Every way to watch this episode in the requested country — a dozen or so
    /// per episode, of which at most one pair is HBO Max. Filtering is the
    /// mapper's job: the server ignores the `filter:` argument on this field, so
    /// asking for less is not an option.
    let offers: [JustWatchOfferEntity]?
}

struct JustWatchEpisodeContentEntity: Codable, Sendable, Hashable {
    let seasonNumber: Int?
    let episodeNumber: Int?
}

struct JustWatchOfferEntity: Codable, Sendable, Hashable {
    let package: JustWatchPackageEntity?
    /// A `String?` rather than a `URL?` on purpose. `URL` decoding is not
    /// forgiving, and one offer with a malformed link — for a service this
    /// feature does not even look at — must not cost the whole show its
    /// decoding. Turning the text into a `URL` is the mapper's decision, and
    /// there it is a `nil` rather than a throw.
    let deeplinkURL: String?
}

/// The service behind an offer. `technicalName` is JustWatch's stable machine
/// name — `max`, `netflix`, `amazon` — as opposed to the display name, which is
/// localized and has already been renamed once for this very service.
struct JustWatchPackageEntity: Codable, Sendable, Hashable {
    let technicalName: String?
}

// MARK: - Document

/// Written by hand rather than generated by `@Document`.
///
/// The macro emits a bare field name per property, which is right for the Rick
/// and Morty schema and cannot work here: three of these fields take arguments
/// (`content(country:language:)`, `offers(country:platform:)`,
/// `deeplinkURL(platform:)`), and the root of the selection is an inline
/// fragment — `node(id:)` returns the `Node` interface, so the show's own fields
/// are only reachable through `... on Show`.
///
/// It lives on the entity anyway, next to the properties it mirrors, so adding a
/// field above means editing the adjacent lines rather than hunting for a string
/// literal in the query.
extension JustWatchShowEntity: GraphQLDocumentConvertible {
    /// - Note: `depth` is ignored. The selection set is fixed — this shape is
    ///   pinned by observation against a server whose introspection is disabled,
    ///   so there is nothing to expand or truncate. Same reasoning as
    ///   `GraphQLPageResponse`.
    static func document(depth: Int) -> String {
        """
        ... on Show {
          seasons {
            content(country: $country, language: $language) {
              seasonNumber
            }
            episodes {
              content(country: $country, language: $language) {
                seasonNumber
                episodeNumber
              }
              offers(country: $country, platform: WEB) {
                package {
                  technicalName
                }
                deeplinkURL(platform: IOS)
              }
            }
          }
        }
        """
    }
}
